name         '3fs-composer'
version      '0.0.1'
source       'https://github.com/3fs/puppet-composer'
author       '3fs'
license      'MIT License'
summary      'Simple puppet module that installs composer - dependency manager for PHP.'
description  'Simple puppet module that installs composer - dependency manager for PHP.'
project_page 'https://github.com/3fs/puppet-composer'
